/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as KonsultacijeRouteImport } from './routes/konsultacije'
import { Route as PolitikaPrivatnostiRouteImport } from './routes/politika-privatnosti'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UsloviKoriscenjaRouteImport } from './routes/uslovi-koriscenja'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PrirucnikSlugRouteImport } from './routes/prirucnik.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminKonsultacijeRouteImport } from './routes/_authenticated/admin.konsultacije'
import { Route as AuthenticatedAdminNalogRouteImport } from './routes/_authenticated/admin.nalog'
import { Route as AuthenticatedAdminPodesavanjaRouteImport } from './routes/_authenticated/admin.podesavanja'
import { Route as AuthenticatedAdminTekstoviRouteImport } from './routes/_authenticated/admin.tekstovi'
import { Route as AuthenticatedAdminBesplatnoIndexRouteImport } from './routes/_authenticated/admin.besplatno.index'
import { Route as AuthenticatedAdminBesplatnoIdRouteImport } from './routes/_authenticated/admin.besplatno.$id'
import { Route as AuthenticatedAdminBesplatnoNoviRouteImport } from './routes/_authenticated/admin.besplatno.novi'
import { Route as AuthenticatedAdminMedijiIndexRouteImport } from './routes/_authenticated/admin.mediji.index'
import { Route as AuthenticatedAdminMedijiIdRouteImport } from './routes/_authenticated/admin.mediji.$id'
import { Route as AuthenticatedAdminMedijiNoviRouteImport } from './routes/_authenticated/admin.mediji.novi'
import { Route as AuthenticatedAdminProizvodiIndexRouteImport } from './routes/_authenticated/admin.proizvodi.index'
import { Route as AuthenticatedAdminProizvodiIdRouteImport } from './routes/_authenticated/admin.proizvodi.$id'
import { Route as AuthenticatedAdminProizvodiNoviRouteImport } from './routes/_authenticated/admin.proizvodi.novi'
import { Route as AuthenticatedAdminWebinariIndexRouteImport } from './routes/_authenticated/admin.webinari.index'
import { Route as AuthenticatedAdminWebinariIdRouteImport } from './routes/_authenticated/admin.webinari.$id'
import { Route as AuthenticatedAdminWebinariNoviRouteImport } from './routes/_authenticated/admin.webinari.novi'
import { Route as ApiPublicFileSplatRouteImport } from './routes/api/public/file.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsultacijeRoute = KonsultacijeRouteImport.update({
  id: '/konsultacije',
  path: '/konsultacije',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaPrivatnostiRoute = PolitikaPrivatnostiRouteImport.update({
  id: '/politika-privatnosti',
  path: '/politika-privatnosti',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UsloviKoriscenjaRoute = UsloviKoriscenjaRouteImport.update({
  id: '/uslovi-koriscenja',
  path: '/uslovi-koriscenja',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PrirucnikSlugRoute = PrirucnikSlugRouteImport.update({
  id: '/prirucnik/$slug',
  path: '/prirucnik/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminKonsultacijeRoute =
  AuthenticatedAdminKonsultacijeRouteImport.update({
    id: '/konsultacije',
    path: '/konsultacije',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNalogRoute = AuthenticatedAdminNalogRouteImport.update({
  id: '/nalog',
  path: '/nalog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPodesavanjaRoute =
  AuthenticatedAdminPodesavanjaRouteImport.update({
    id: '/podesavanja',
    path: '/podesavanja',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTekstoviRoute =
  AuthenticatedAdminTekstoviRouteImport.update({
    id: '/tekstovi',
    path: '/tekstovi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBesplatnoIndexRoute =
  AuthenticatedAdminBesplatnoIndexRouteImport.update({
    id: '/besplatno/',
    path: '/besplatno/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBesplatnoIdRoute =
  AuthenticatedAdminBesplatnoIdRouteImport.update({
    id: '/besplatno/$id',
    path: '/besplatno/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBesplatnoNoviRoute =
  AuthenticatedAdminBesplatnoNoviRouteImport.update({
    id: '/besplatno/novi',
    path: '/besplatno/novi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMedijiIndexRoute =
  AuthenticatedAdminMedijiIndexRouteImport.update({
    id: '/mediji/',
    path: '/mediji/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMedijiIdRoute =
  AuthenticatedAdminMedijiIdRouteImport.update({
    id: '/mediji/$id',
    path: '/mediji/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMedijiNoviRoute =
  AuthenticatedAdminMedijiNoviRouteImport.update({
    id: '/mediji/novi',
    path: '/mediji/novi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProizvodiIndexRoute =
  AuthenticatedAdminProizvodiIndexRouteImport.update({
    id: '/proizvodi/',
    path: '/proizvodi/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProizvodiIdRoute =
  AuthenticatedAdminProizvodiIdRouteImport.update({
    id: '/proizvodi/$id',
    path: '/proizvodi/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProizvodiNoviRoute =
  AuthenticatedAdminProizvodiNoviRouteImport.update({
    id: '/proizvodi/novi',
    path: '/proizvodi/novi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebinariIndexRoute =
  AuthenticatedAdminWebinariIndexRouteImport.update({
    id: '/webinari/',
    path: '/webinari/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebinariIdRoute =
  AuthenticatedAdminWebinariIdRouteImport.update({
    id: '/webinari/$id',
    path: '/webinari/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebinariNoviRoute =
  AuthenticatedAdminWebinariNoviRouteImport.update({
    id: '/webinari/novi',
    path: '/webinari/novi',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicFileSplatRoute = ApiPublicFileSplatRouteImport.update({
  id: '/api/public/file/$',
  path: '/api/public/file/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/konsultacije': typeof KonsultacijeRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslovi-koriscenja': typeof UsloviKoriscenjaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/prirucnik/$slug': typeof PrirucnikSlugRoute
  '/admin/konsultacije': typeof AuthenticatedAdminKonsultacijeRoute
  '/admin/nalog': typeof AuthenticatedAdminNalogRoute
  '/admin/podesavanja': typeof AuthenticatedAdminPodesavanjaRoute
  '/admin/tekstovi': typeof AuthenticatedAdminTekstoviRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/besplatno/$id': typeof AuthenticatedAdminBesplatnoIdRoute
  '/admin/besplatno/novi': typeof AuthenticatedAdminBesplatnoNoviRoute
  '/admin/mediji/$id': typeof AuthenticatedAdminMedijiIdRoute
  '/admin/mediji/novi': typeof AuthenticatedAdminMedijiNoviRoute
  '/admin/proizvodi/$id': typeof AuthenticatedAdminProizvodiIdRoute
  '/admin/proizvodi/novi': typeof AuthenticatedAdminProizvodiNoviRoute
  '/admin/webinari/$id': typeof AuthenticatedAdminWebinariIdRoute
  '/admin/webinari/novi': typeof AuthenticatedAdminWebinariNoviRoute
  '/api/public/file/$': typeof ApiPublicFileSplatRoute
  '/admin/besplatno/': typeof AuthenticatedAdminBesplatnoIndexRoute
  '/admin/mediji/': typeof AuthenticatedAdminMedijiIndexRoute
  '/admin/proizvodi/': typeof AuthenticatedAdminProizvodiIndexRoute
  '/admin/webinari/': typeof AuthenticatedAdminWebinariIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/konsultacije': typeof KonsultacijeRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslovi-koriscenja': typeof UsloviKoriscenjaRoute
  '/prirucnik/$slug': typeof PrirucnikSlugRoute
  '/admin/konsultacije': typeof AuthenticatedAdminKonsultacijeRoute
  '/admin/nalog': typeof AuthenticatedAdminNalogRoute
  '/admin/podesavanja': typeof AuthenticatedAdminPodesavanjaRoute
  '/admin/tekstovi': typeof AuthenticatedAdminTekstoviRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/besplatno/$id': typeof AuthenticatedAdminBesplatnoIdRoute
  '/admin/besplatno/novi': typeof AuthenticatedAdminBesplatnoNoviRoute
  '/admin/mediji/$id': typeof AuthenticatedAdminMedijiIdRoute
  '/admin/mediji/novi': typeof AuthenticatedAdminMedijiNoviRoute
  '/admin/proizvodi/$id': typeof AuthenticatedAdminProizvodiIdRoute
  '/admin/proizvodi/novi': typeof AuthenticatedAdminProizvodiNoviRoute
  '/admin/webinari/$id': typeof AuthenticatedAdminWebinariIdRoute
  '/admin/webinari/novi': typeof AuthenticatedAdminWebinariNoviRoute
  '/api/public/file/$': typeof ApiPublicFileSplatRoute
  '/admin/besplatno': typeof AuthenticatedAdminBesplatnoIndexRoute
  '/admin/mediji': typeof AuthenticatedAdminMedijiIndexRoute
  '/admin/proizvodi': typeof AuthenticatedAdminProizvodiIndexRoute
  '/admin/webinari': typeof AuthenticatedAdminWebinariIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/konsultacije': typeof KonsultacijeRoute
  '/politika-privatnosti': typeof PolitikaPrivatnostiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uslovi-koriscenja': typeof UsloviKoriscenjaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/prirucnik/$slug': typeof PrirucnikSlugRoute
  '/_authenticated/admin/konsultacije': typeof AuthenticatedAdminKonsultacijeRoute
  '/_authenticated/admin/nalog': typeof AuthenticatedAdminNalogRoute
  '/_authenticated/admin/podesavanja': typeof AuthenticatedAdminPodesavanjaRoute
  '/_authenticated/admin/tekstovi': typeof AuthenticatedAdminTekstoviRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/besplatno/$id': typeof AuthenticatedAdminBesplatnoIdRoute
  '/_authenticated/admin/besplatno/novi': typeof AuthenticatedAdminBesplatnoNoviRoute
  '/_authenticated/admin/mediji/$id': typeof AuthenticatedAdminMedijiIdRoute
  '/_authenticated/admin/mediji/novi': typeof AuthenticatedAdminMedijiNoviRoute
  '/_authenticated/admin/proizvodi/$id': typeof AuthenticatedAdminProizvodiIdRoute
  '/_authenticated/admin/proizvodi/novi': typeof AuthenticatedAdminProizvodiNoviRoute
  '/_authenticated/admin/webinari/$id': typeof AuthenticatedAdminWebinariIdRoute
  '/_authenticated/admin/webinari/novi': typeof AuthenticatedAdminWebinariNoviRoute
  '/api/public/file/$': typeof ApiPublicFileSplatRoute
  '/_authenticated/admin/besplatno/': typeof AuthenticatedAdminBesplatnoIndexRoute
  '/_authenticated/admin/mediji/': typeof AuthenticatedAdminMedijiIndexRoute
  '/_authenticated/admin/proizvodi/': typeof AuthenticatedAdminProizvodiIndexRoute
  '/_authenticated/admin/webinari/': typeof AuthenticatedAdminWebinariIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/konsultacije'
    | '/politika-privatnosti'
    | '/sitemap.xml'
    | '/uslovi-koriscenja'
    | '/admin'
    | '/prirucnik/$slug'
    | '/admin/konsultacije'
    | '/admin/nalog'
    | '/admin/podesavanja'
    | '/admin/tekstovi'
    | '/admin/'
    | '/admin/besplatno/$id'
    | '/admin/besplatno/novi'
    | '/admin/mediji/$id'
    | '/admin/mediji/novi'
    | '/admin/proizvodi/$id'
    | '/admin/proizvodi/novi'
    | '/admin/webinari/$id'
    | '/admin/webinari/novi'
    | '/api/public/file/$'
    | '/admin/besplatno/'
    | '/admin/mediji/'
    | '/admin/proizvodi/'
    | '/admin/webinari/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/konsultacije'
    | '/politika-privatnosti'
    | '/sitemap.xml'
    | '/uslovi-koriscenja'
    | '/prirucnik/$slug'
    | '/admin/konsultacije'
    | '/admin/nalog'
    | '/admin/podesavanja'
    | '/admin/tekstovi'
    | '/admin'
    | '/admin/besplatno/$id'
    | '/admin/besplatno/novi'
    | '/admin/mediji/$id'
    | '/admin/mediji/novi'
    | '/admin/proizvodi/$id'
    | '/admin/proizvodi/novi'
    | '/admin/webinari/$id'
    | '/admin/webinari/novi'
    | '/api/public/file/$'
    | '/admin/besplatno'
    | '/admin/mediji'
    | '/admin/proizvodi'
    | '/admin/webinari'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/konsultacije'
    | '/politika-privatnosti'
    | '/sitemap.xml'
    | '/uslovi-koriscenja'
    | '/_authenticated/admin'
    | '/prirucnik/$slug'
    | '/_authenticated/admin/konsultacije'
    | '/_authenticated/admin/nalog'
    | '/_authenticated/admin/podesavanja'
    | '/_authenticated/admin/tekstovi'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/besplatno/$id'
    | '/_authenticated/admin/besplatno/novi'
    | '/_authenticated/admin/mediji/$id'
    | '/_authenticated/admin/mediji/novi'
    | '/_authenticated/admin/proizvodi/$id'
    | '/_authenticated/admin/proizvodi/novi'
    | '/_authenticated/admin/webinari/$id'
    | '/_authenticated/admin/webinari/novi'
    | '/api/public/file/$'
    | '/_authenticated/admin/besplatno/'
    | '/_authenticated/admin/mediji/'
    | '/_authenticated/admin/proizvodi/'
    | '/_authenticated/admin/webinari/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  KonsultacijeRoute: typeof KonsultacijeRoute
  PolitikaPrivatnostiRoute: typeof PolitikaPrivatnostiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UsloviKoriscenjaRoute: typeof UsloviKoriscenjaRoute
  PrirucnikSlugRoute: typeof PrirucnikSlugRoute
  ApiPublicFileSplatRoute: typeof ApiPublicFileSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsultacije': {
      id: '/konsultacije'
      path: '/konsultacije'
      fullPath: '/konsultacije'
      preLoaderRoute: typeof KonsultacijeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika-privatnosti': {
      id: '/politika-privatnosti'
      path: '/politika-privatnosti'
      fullPath: '/politika-privatnosti'
      preLoaderRoute: typeof PolitikaPrivatnostiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslovi-koriscenja': {
      id: '/uslovi-koriscenja'
      path: '/uslovi-koriscenja'
      fullPath: '/uslovi-koriscenja'
      preLoaderRoute: typeof UsloviKoriscenjaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/prirucnik/$slug': {
      id: '/prirucnik/$slug'
      path: '/prirucnik/$slug'
      fullPath: '/prirucnik/$slug'
      preLoaderRoute: typeof PrirucnikSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/konsultacije': {
      id: '/_authenticated/admin/konsultacije'
      path: '/konsultacije'
      fullPath: '/admin/konsultacije'
      preLoaderRoute: typeof AuthenticatedAdminKonsultacijeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/nalog': {
      id: '/_authenticated/admin/nalog'
      path: '/nalog'
      fullPath: '/admin/nalog'
      preLoaderRoute: typeof AuthenticatedAdminNalogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/podesavanja': {
      id: '/_authenticated/admin/podesavanja'
      path: '/podesavanja'
      fullPath: '/admin/podesavanja'
      preLoaderRoute: typeof AuthenticatedAdminPodesavanjaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tekstovi': {
      id: '/_authenticated/admin/tekstovi'
      path: '/tekstovi'
      fullPath: '/admin/tekstovi'
      preLoaderRoute: typeof AuthenticatedAdminTekstoviRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/besplatno/': {
      id: '/_authenticated/admin/besplatno/'
      path: '/besplatno'
      fullPath: '/admin/besplatno/'
      preLoaderRoute: typeof AuthenticatedAdminBesplatnoIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/besplatno/$id': {
      id: '/_authenticated/admin/besplatno/$id'
      path: '/besplatno/$id'
      fullPath: '/admin/besplatno/$id'
      preLoaderRoute: typeof AuthenticatedAdminBesplatnoIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/besplatno/novi': {
      id: '/_authenticated/admin/besplatno/novi'
      path: '/besplatno/novi'
      fullPath: '/admin/besplatno/novi'
      preLoaderRoute: typeof AuthenticatedAdminBesplatnoNoviRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mediji/': {
      id: '/_authenticated/admin/mediji/'
      path: '/mediji'
      fullPath: '/admin/mediji/'
      preLoaderRoute: typeof AuthenticatedAdminMedijiIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mediji/$id': {
      id: '/_authenticated/admin/mediji/$id'
      path: '/mediji/$id'
      fullPath: '/admin/mediji/$id'
      preLoaderRoute: typeof AuthenticatedAdminMedijiIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mediji/novi': {
      id: '/_authenticated/admin/mediji/novi'
      path: '/mediji/novi'
      fullPath: '/admin/mediji/novi'
      preLoaderRoute: typeof AuthenticatedAdminMedijiNoviRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proizvodi/': {
      id: '/_authenticated/admin/proizvodi/'
      path: '/proizvodi'
      fullPath: '/admin/proizvodi/'
      preLoaderRoute: typeof AuthenticatedAdminProizvodiIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proizvodi/$id': {
      id: '/_authenticated/admin/proizvodi/$id'
      path: '/proizvodi/$id'
      fullPath: '/admin/proizvodi/$id'
      preLoaderRoute: typeof AuthenticatedAdminProizvodiIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/proizvodi/novi': {
      id: '/_authenticated/admin/proizvodi/novi'
      path: '/proizvodi/novi'
      fullPath: '/admin/proizvodi/novi'
      preLoaderRoute: typeof AuthenticatedAdminProizvodiNoviRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/webinari/': {
      id: '/_authenticated/admin/webinari/'
      path: '/webinari'
      fullPath: '/admin/webinari/'
      preLoaderRoute: typeof AuthenticatedAdminWebinariIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/webinari/$id': {
      id: '/_authenticated/admin/webinari/$id'
      path: '/webinari/$id'
      fullPath: '/admin/webinari/$id'
      preLoaderRoute: typeof AuthenticatedAdminWebinariIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/webinari/novi': {
      id: '/_authenticated/admin/webinari/novi'
      path: '/webinari/novi'
      fullPath: '/admin/webinari/novi'
      preLoaderRoute: typeof AuthenticatedAdminWebinariNoviRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/file/$': {
      id: '/api/public/file/$'
      path: '/api/public/file/$'
      fullPath: '/api/public/file/$'
      preLoaderRoute: typeof ApiPublicFileSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminKonsultacijeRoute: typeof AuthenticatedAdminKonsultacijeRoute
  AuthenticatedAdminNalogRoute: typeof AuthenticatedAdminNalogRoute
  AuthenticatedAdminPodesavanjaRoute: typeof AuthenticatedAdminPodesavanjaRoute
  AuthenticatedAdminTekstoviRoute: typeof AuthenticatedAdminTekstoviRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBesplatnoIdRoute: typeof AuthenticatedAdminBesplatnoIdRoute
  AuthenticatedAdminBesplatnoNoviRoute: typeof AuthenticatedAdminBesplatnoNoviRoute
  AuthenticatedAdminMedijiIdRoute: typeof AuthenticatedAdminMedijiIdRoute
  AuthenticatedAdminMedijiNoviRoute: typeof AuthenticatedAdminMedijiNoviRoute
  AuthenticatedAdminProizvodiIdRoute: typeof AuthenticatedAdminProizvodiIdRoute
  AuthenticatedAdminProizvodiNoviRoute: typeof AuthenticatedAdminProizvodiNoviRoute
  AuthenticatedAdminWebinariIdRoute: typeof AuthenticatedAdminWebinariIdRoute
  AuthenticatedAdminWebinariNoviRoute: typeof AuthenticatedAdminWebinariNoviRoute
  AuthenticatedAdminBesplatnoIndexRoute: typeof AuthenticatedAdminBesplatnoIndexRoute
  AuthenticatedAdminMedijiIndexRoute: typeof AuthenticatedAdminMedijiIndexRoute
  AuthenticatedAdminProizvodiIndexRoute: typeof AuthenticatedAdminProizvodiIndexRoute
  AuthenticatedAdminWebinariIndexRoute: typeof AuthenticatedAdminWebinariIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminKonsultacijeRoute: AuthenticatedAdminKonsultacijeRoute,
  AuthenticatedAdminNalogRoute: AuthenticatedAdminNalogRoute,
  AuthenticatedAdminPodesavanjaRoute: AuthenticatedAdminPodesavanjaRoute,
  AuthenticatedAdminTekstoviRoute: AuthenticatedAdminTekstoviRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBesplatnoIdRoute: AuthenticatedAdminBesplatnoIdRoute,
  AuthenticatedAdminBesplatnoNoviRoute: AuthenticatedAdminBesplatnoNoviRoute,
  AuthenticatedAdminMedijiIdRoute: AuthenticatedAdminMedijiIdRoute,
  AuthenticatedAdminMedijiNoviRoute: AuthenticatedAdminMedijiNoviRoute,
  AuthenticatedAdminProizvodiIdRoute: AuthenticatedAdminProizvodiIdRoute,
  AuthenticatedAdminProizvodiNoviRoute: AuthenticatedAdminProizvodiNoviRoute,
  AuthenticatedAdminWebinariIdRoute: AuthenticatedAdminWebinariIdRoute,
  AuthenticatedAdminWebinariNoviRoute: AuthenticatedAdminWebinariNoviRoute,
  AuthenticatedAdminBesplatnoIndexRoute: AuthenticatedAdminBesplatnoIndexRoute,
  AuthenticatedAdminMedijiIndexRoute: AuthenticatedAdminMedijiIndexRoute,
  AuthenticatedAdminProizvodiIndexRoute: AuthenticatedAdminProizvodiIndexRoute,
  AuthenticatedAdminWebinariIndexRoute: AuthenticatedAdminWebinariIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  KonsultacijeRoute: KonsultacijeRoute,
  PolitikaPrivatnostiRoute: PolitikaPrivatnostiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UsloviKoriscenjaRoute: UsloviKoriscenjaRoute,
  PrirucnikSlugRoute: PrirucnikSlugRoute,
  ApiPublicFileSplatRoute: ApiPublicFileSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
